# -*- coding: utf-8 -*-
"""Regresión_lineal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NYxSmVRqXbHZbFEO4qNOH6lnnpqPspGd
"""

import main as ajuste
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import seaborn as sns
#from matplotlib import rc

datos1=pd.read_csv("incident_angle_030347.txt", delimiter="\t",skiprows=1)
datos2=pd.read_csv("refraction_trans_ang_030333.txt", delimiter="\t",skiprows=1)

datos1
datos2

plt.plot(datos1['t'],datos1['θ'],label='Ángulo incidente')
plt.plot(datos2['t'],datos2['θ'],label='Ángulo de refracción')
plt.xlabel('Tiempo [s]')
plt.ylabel('Ángulo [°]')
plt.legend(loc='lower left')
plt.savefig("gráfica_preliminar.png")

ang_inc=datos1["θ"][57:]-90
ang_ref=datos2["θ"][57:]+90

ang_ref

X=np.array(np.sin(ang_inc*np.pi/180))
Y=np.array(np.sin(ang_ref*np.pi/180))
print(X,Y)

print("El punto de corte con el eje y del ajuste es "+str(ajuste.A(X,Y))) #Punto de corte
print("La pendiente del ajuste es "+str(ajuste.B(X,Y))) #Pendiente (Gelatina/Aire)
print("El coeficiente de correlación del ajuste es "+str(ajuste.coeficiente_correlacion(X,Y)))

print("El coeficiente de correlación del ajuste es de "+str(ajuste.coeficiente_correlacion(X,Y)))

ajuste.fit(X,Y)

plt.scatter(X,Y,label="Datos")
plt.plot(X,ajuste.ajuste(X,Y,X),label=f"{ajuste.fit(X,Y)}")
plt.xlabel("t(s)")
plt.ylabel("theta(°)")
plt.legend()
plt.savefig("Ajuste vs datos")

"""Para hallar el índice de refracción de la geltina se debe multiplicar la pendiente del ajuste obtenido por el índice de refracción del aire.

Esto debido a que la pendiente del ajuste corresponde a la razón entre el índice de refracción de la geltina y el índice de refracción del aire.

Se tomará el índice de refracción del aire como 1,00029.
"""

print("El índice de refracción de la gelatina es "+str(ajuste.B(X,Y)*1.00029))

"""**Forma matricial**"""

Xaumentada=np.ones((len(X),2))
Xaumentada[:,0]=X
X_t_X=np.dot(Xaumentada.T,Xaumentada)

b=np.dot(np.linalg.inv(X_t_X),np.dot(Xaumentada.T,Y))

b

print("El ajuste lineal obtenido es: y = "+str(b[0])+"x + "+str(b[1]))

print("El índice de refracción de la gelatina es "+str(b[0]*1.00029))

"""**Conclusiones**

Se ve que los ajustes lineales obtenidos (a través del método de mínimos cuadrados) por medio de la forma matricial y por definición son bastante cercanos. Es por esto que el índice de refracción obtenido de ambos ajuste es aproximadamente el mismo, la diferencia entre los valores obtenidos se ve a partir de la 15 cifra significativa.
"""